//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Armoire.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Armoire.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute.
        /// </summary>
        public static string cmn_attr {
            get {
                return ResourceManager.GetString("cmn_attr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bound Module.
        /// </summary>
        public static string cmn_bind {
            get {
                return ResourceManager.GetString("cmn_bind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string cmn_button_change {
            get {
                return ResourceManager.GetString("cmn_button_change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string cmn_button_edit {
            get {
                return ResourceManager.GetString("cmn_button_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character.
        /// </summary>
        public static string cmn_chara {
            get {
                return ResourceManager.GetString("cmn_chara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Costume.
        /// </summary>
        public static string cmn_cos {
            get {
                return ResourceManager.GetString("cmn_cos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item .
        /// </summary>
        public static string cmn_cos_item {
            get {
                return ResourceManager.GetString("cmn_cos_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string cmn_day {
            get {
                return ResourceManager.GetString("cmn_day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string cmn_details {
            get {
                return ResourceManager.GetString("cmn_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string cmn_exit {
            get {
                return ResourceManager.GetString("cmn_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string cmn_id {
            get {
                return ResourceManager.GetString("cmn_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        public static string cmn_index {
            get {
                return ResourceManager.GetString("cmn_index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No..
        /// </summary>
        public static string cmn_item_no {
            get {
                return ResourceManager.GetString("cmn_item_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string cmn_month {
            get {
                return ResourceManager.GetString("cmn_month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string cmn_name {
            get {
                return ResourceManager.GetString("cmn_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object ID.
        /// </summary>
        public static string cmn_objid {
            get {
                return ResourceManager.GetString("cmn_objid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object UID.
        /// </summary>
        public static string cmn_objuid {
            get {
                return ResourceManager.GetString("cmn_objuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parts.
        /// </summary>
        public static string cmn_parts {
            get {
                return ResourceManager.GetString("cmn_parts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preset.
        /// </summary>
        public static string cmn_preset {
            get {
                return ResourceManager.GetString("cmn_preset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string cmn_price {
            get {
                return ResourceManager.GetString("cmn_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string cmn_year {
            get {
                return ResourceManager.GetString("cmn_year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string db_edit_obj {
            get {
                return ResourceManager.GetString("db_edit_obj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string db_edit_spr {
            get {
                return ResourceManager.GetString("db_edit_spr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string db_edit_tex {
            get {
                return ResourceManager.GetString("db_edit_tex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To CSV.
        /// </summary>
        public static string file_csv {
            get {
                return ResourceManager.GetString("file_csv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleaner.
        /// </summary>
        public static string file_db_clean {
            get {
                return ResourceManager.GetString("file_db_clean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string file_open {
            get {
                return ResourceManager.GetString("file_open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string file_save {
            get {
                return ResourceManager.GetString("file_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As.
        /// </summary>
        public static string file_saveas {
            get {
                return ResourceManager.GetString("file_saveas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string file_title {
            get {
                return ResourceManager.GetString("file_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wizard.
        /// </summary>
        public static string file_wizard {
            get {
                return ResourceManager.GetString("file_wizard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap info_n {
            get {
                object obj = ResourceManager.GetObject("info_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap info_p {
            get {
                object obj = ResourceManager.GetObject("info_p", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap item {
            get {
                object obj = ResourceManager.GetObject("item", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap item_ct {
            get {
                object obj = ResourceManager.GetObject("item_ct", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap item_fs {
            get {
                object obj = ResourceManager.GetObject("item_fs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap item_n {
            get {
                object obj = ResourceManager.GetObject("item_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap md_dummy {
            get {
                object obj = ResourceManager.GetObject("md_dummy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armoire (Character Item Tables).
        /// </summary>
        public static string title_chritm {
            get {
                return ResourceManager.GetString("title_chritm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armoire (Customize Items).
        /// </summary>
        public static string title_custom {
            get {
                return ResourceManager.GetString("title_custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armoire (Object Database Editor).
        /// </summary>
        public static string title_edit_obj {
            get {
                return ResourceManager.GetString("title_edit_obj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armoire (Sprite Database Editor).
        /// </summary>
        public static string title_edit_spr {
            get {
                return ResourceManager.GetString("title_edit_spr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armoire (Texture Database Editor).
        /// </summary>
        public static string title_edit_tex {
            get {
                return ResourceManager.GetString("title_edit_tex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armoire (Modules).
        /// </summary>
        public static string title_module {
            get {
                return ResourceManager.GetString("title_module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armoire (Module Wizard).
        /// </summary>
        public static string title_wizard {
            get {
                return ResourceManager.GetString("title_wizard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character Item Editor.
        /// </summary>
        public static string window_chritm {
            get {
                return ResourceManager.GetString("window_chritm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customize Item Editor.
        /// </summary>
        public static string window_custom {
            get {
                return ResourceManager.GetString("window_custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DB Editors.
        /// </summary>
        public static string window_db_title {
            get {
                return ResourceManager.GetString("window_db_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module Editor.
        /// </summary>
        public static string window_module {
            get {
                return ResourceManager.GetString("window_module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object DB.
        /// </summary>
        public static string window_obj {
            get {
                return ResourceManager.GetString("window_obj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string window_preview {
            get {
                return ResourceManager.GetString("window_preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprite DB.
        /// </summary>
        public static string window_spr {
            get {
                return ResourceManager.GetString("window_spr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texture DB.
        /// </summary>
        public static string window_tex {
            get {
                return ResourceManager.GetString("window_tex", resourceCulture);
            }
        }
    }
}
