//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Armoire.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Armoire.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centre.
        /// </summary>
        public static string align_centre {
            get {
                return ResourceManager.GetString("align_centre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        public static string align_left {
            get {
                return ResourceManager.GetString("align_left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        public static string align_right {
            get {
                return ResourceManager.GetString("align_right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Alignment.
        /// </summary>
        public static string align_text {
            get {
                return ResourceManager.GetString("align_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string cmn_add {
            get {
                return ResourceManager.GetString("cmn_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply &amp; Close.
        /// </summary>
        public static string cmn_apply {
            get {
                return ResourceManager.GetString("cmn_apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute.
        /// </summary>
        public static string cmn_attr {
            get {
                return ResourceManager.GetString("cmn_attr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bound Module.
        /// </summary>
        public static string cmn_bind {
            get {
                return ResourceManager.GetString("cmn_bind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string cmn_button_change {
            get {
                return ResourceManager.GetString("cmn_button_change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string cmn_button_edit {
            get {
                return ResourceManager.GetString("cmn_button_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character.
        /// </summary>
        public static string cmn_chara {
            get {
                return ResourceManager.GetString("cmn_chara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close File.
        /// </summary>
        public static string cmn_close {
            get {
                return ResourceManager.GetString("cmn_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close without Saving.
        /// </summary>
        public static string cmn_close_n {
            get {
                return ResourceManager.GetString("cmn_close_n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Costume.
        /// </summary>
        public static string cmn_cos {
            get {
                return ResourceManager.GetString("cmn_cos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item .
        /// </summary>
        public static string cmn_cos_item {
            get {
                return ResourceManager.GetString("cmn_cos_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string cmn_day {
            get {
                return ResourceManager.GetString("cmn_day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string cmn_details {
            get {
                return ResourceManager.GetString("cmn_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENTER VALUE HERE.
        /// </summary>
        public static string cmn_enter_value {
            get {
                return ResourceManager.GetString("cmn_enter_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string cmn_error {
            get {
                return ResourceManager.GetString("cmn_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string cmn_exit {
            get {
                return ResourceManager.GetString("cmn_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finalise.
        /// </summary>
        public static string cmn_finish {
            get {
                return ResourceManager.GetString("cmn_finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Hair Swapping.
        /// </summary>
        public static string cmn_hair_swap {
            get {
                return ResourceManager.GetString("cmn_hair_swap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string cmn_id {
            get {
                return ResourceManager.GetString("cmn_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        public static string cmn_index {
            get {
                return ResourceManager.GetString("cmn_index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items.
        /// </summary>
        public static string cmn_item_list {
            get {
                return ResourceManager.GetString("cmn_item_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No..
        /// </summary>
        public static string cmn_item_no {
            get {
                return ResourceManager.GetString("cmn_item_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Number.
        /// </summary>
        public static string cmn_item_nofull {
            get {
                return ResourceManager.GetString("cmn_item_nofull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Item Type.
        /// </summary>
        public static string cmn_item_type {
            get {
                return ResourceManager.GetString("cmn_item_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        public static string cmn_lang {
            get {
                return ResourceManager.GetString("cmn_lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string cmn_month {
            get {
                return ResourceManager.GetString("cmn_month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string cmn_name {
            get {
                return ResourceManager.GetString("cmn_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string cmn_no {
            get {
                return ResourceManager.GetString("cmn_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objset Entries.
        /// </summary>
        public static string cmn_obj_entry {
            get {
                return ResourceManager.GetString("cmn_obj_entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object ID.
        /// </summary>
        public static string cmn_objid {
            get {
                return ResourceManager.GetString("cmn_objid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objects.
        /// </summary>
        public static string cmn_objs {
            get {
                return ResourceManager.GetString("cmn_objs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object UID.
        /// </summary>
        public static string cmn_objuid {
            get {
                return ResourceManager.GetString("cmn_objuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original Item.
        /// </summary>
        public static string cmn_org_itm {
            get {
                return ResourceManager.GetString("cmn_org_itm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parts.
        /// </summary>
        public static string cmn_parts {
            get {
                return ResourceManager.GetString("cmn_parts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preset.
        /// </summary>
        public static string cmn_preset {
            get {
                return ResourceManager.GetString("cmn_preset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview Image.
        /// </summary>
        public static string cmn_preview_img {
            get {
                return ResourceManager.GetString("cmn_preview_img", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string cmn_price {
            get {
                return ResourceManager.GetString("cmn_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string cmn_remove {
            get {
                return ResourceManager.GetString("cmn_remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove All.
        /// </summary>
        public static string cmn_remove_all {
            get {
                return ResourceManager.GetString("cmn_remove_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace All.
        /// </summary>
        public static string cmn_replace {
            get {
                return ResourceManager.GetString("cmn_replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string cmn_sel {
            get {
                return ResourceManager.GetString("cmn_sel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short File Name.
        /// </summary>
        public static string cmn_short_name {
            get {
                return ResourceManager.GetString("cmn_short_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprites.
        /// </summary>
        public static string cmn_sprs {
            get {
                return ResourceManager.GetString("cmn_sprs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is this okay?.
        /// </summary>
        public static string cmn_sure {
            get {
                return ResourceManager.GetString("cmn_sure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporary.
        /// </summary>
        public static string cmn_temp {
            get {
                return ResourceManager.GetString("cmn_temp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texture Entries.
        /// </summary>
        public static string cmn_tex_entry {
            get {
                return ResourceManager.GetString("cmn_tex_entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Textures.
        /// </summary>
        public static string cmn_texs {
            get {
                return ResourceManager.GetString("cmn_texs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Armoire.
        /// </summary>
        public static string cmn_update {
            get {
                return ResourceManager.GetString("cmn_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string cmn_year {
            get {
                return ResourceManager.GetString("cmn_year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string cmn_yes {
            get {
                return ResourceManager.GetString("cmn_yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character Costume IDs.
        /// </summary>
        public static string conflict_cos_id {
            get {
                return ResourceManager.GetString("conflict_cos_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customize Item IDs.
        /// </summary>
        public static string conflict_custom_id {
            get {
                return ResourceManager.GetString("conflict_custom_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customize Item Sorting Indexes.
        /// </summary>
        public static string conflict_custom_sort {
            get {
                return ResourceManager.GetString("conflict_custom_sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farc File Names.
        /// </summary>
        public static string conflict_farc {
            get {
                return ResourceManager.GetString("conflict_farc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character Item Nos.
        /// </summary>
        public static string conflict_item_id {
            get {
                return ResourceManager.GetString("conflict_item_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module IDs.
        /// </summary>
        public static string conflict_module_id {
            get {
                return ResourceManager.GetString("conflict_module_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module Sorting Indexes.
        /// </summary>
        public static string conflict_module_sort {
            get {
                return ResourceManager.GetString("conflict_module_sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprites.
        /// </summary>
        public static string conflict_spr {
            get {
                return ResourceManager.GetString("conflict_spr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprite Sets.
        /// </summary>
        public static string conflict_spr_set {
            get {
                return ResourceManager.GetString("conflict_spr_set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprite Texture IDs.
        /// </summary>
        public static string conflict_spr_tex {
            get {
                return ResourceManager.GetString("conflict_spr_tex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clashing.
        /// </summary>
        public static string conflict_start {
            get {
                return ResourceManager.GetString("conflict_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texture IDs.
        /// </summary>
        public static string conflict_tex_id {
            get {
                return ResourceManager.GetString("conflict_tex_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texture Names.
        /// </summary>
        public static string conflict_tex_name {
            get {
                return ResourceManager.GetString("conflict_tex_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Accessory.
        /// </summary>
        public static string cxt_acc_add {
            get {
                return ResourceManager.GetString("cxt_acc_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Accessory.
        /// </summary>
        public static string cxt_acc_remove {
            get {
                return ResourceManager.GetString("cxt_acc_remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Costume.
        /// </summary>
        public static string cxt_cos_add {
            get {
                return ResourceManager.GetString("cxt_cos_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Costume.
        /// </summary>
        public static string cxt_cos_remove {
            get {
                return ResourceManager.GetString("cxt_cos_remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Item.
        /// </summary>
        public static string cxt_item_add {
            get {
                return ResourceManager.GetString("cxt_item_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Item.
        /// </summary>
        public static string cxt_item_remove {
            get {
                return ResourceManager.GetString("cxt_item_remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Module.
        /// </summary>
        public static string cxt_module_add {
            get {
                return ResourceManager.GetString("cxt_module_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Module.
        /// </summary>
        public static string cxt_module_remove {
            get {
                return ResourceManager.GetString("cxt_module_remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This tab allows you to update and reference compatibility information pertaining to mods hosted on DivaModArchive. While this can help to avoid clashing IDs, it is not fool proof, please check your mods thoroughly to ensure desired compatibility..
        /// </summary>
        public static string dma_blurb {
            get {
                return ResourceManager.GetString("dma_blurb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This process will check EVERY mod in your mods folder and export any conflicts with the base game AND the DMA compatibility information..
        /// </summary>
        public static string dma_check_1 {
            get {
                return ResourceManager.GetString("dma_check_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It may take a very long time and create a large file..
        /// </summary>
        public static string dma_check_2 {
            get {
                return ResourceManager.GetString("dma_check_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check mods for conflicts.
        /// </summary>
        public static string dma_check_conflict {
            get {
                return ResourceManager.GetString("dma_check_conflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download latest compatibility information.
        /// </summary>
        public static string dma_download {
            get {
                return ResourceManager.GetString("dma_download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already updated the database today, would you like to do it again?.
        /// </summary>
        public static string dma_update_already {
            get {
                return ResourceManager.GetString("dma_update_already", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your model&apos;s FARC file..
        /// </summary>
        public static string exp_1 {
            get {
                return ResourceManager.GetString("exp_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your desired value..
        /// </summary>
        public static string exp_2 {
            get {
                return ResourceManager.GetString("exp_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your image must be a 512px x 512px PNG format file..
        /// </summary>
        public static string exp_3 {
            get {
                return ResourceManager.GetString("exp_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That didn&apos;t work. Try opening a file first..
        /// </summary>
        public static string exp_4 {
            get {
                return ResourceManager.GetString("exp_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred with this file: .
        /// </summary>
        public static string exp_5 {
            get {
                return ResourceManager.GetString("exp_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved successfully..
        /// </summary>
        public static string exp_6 {
            get {
                return ResourceManager.GetString("exp_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string file_open {
            get {
                return ResourceManager.GetString("file_open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string file_save {
            get {
                return ResourceManager.GetString("file_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As.
        /// </summary>
        public static string file_saveas {
            get {
                return ResourceManager.GetString("file_saveas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string file_title {
            get {
                return ResourceManager.GetString("file_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wizard.
        /// </summary>
        public static string file_wizard {
            get {
                return ResourceManager.GetString("file_wizard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back Accessory.
        /// </summary>
        public static string item_backacc {
            get {
                return ResourceManager.GetString("item_backacc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body.
        /// </summary>
        public static string item_body {
            get {
                return ResourceManager.GetString("item_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chest Accessory.
        /// </summary>
        public static string item_chestacc {
            get {
                return ResourceManager.GetString("item_chestacc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Lenses.
        /// </summary>
        public static string item_contact {
            get {
                return ResourceManager.GetString("item_contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        public static string item_default {
            get {
                return ResourceManager.GetString("item_default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eye Texture Swap.
        /// </summary>
        public static string item_eye {
            get {
                return ResourceManager.GetString("item_eye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Face Accessory.
        /// </summary>
        public static string item_faceacc {
            get {
                return ResourceManager.GetString("item_faceacc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hair.
        /// </summary>
        public static string item_hair {
            get {
                return ResourceManager.GetString("item_hair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hands.
        /// </summary>
        public static string item_hands {
            get {
                return ResourceManager.GetString("item_hands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head.
        /// </summary>
        public static string item_head {
            get {
                return ResourceManager.GetString("item_head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head Accessory.
        /// </summary>
        public static string item_headacc {
            get {
                return ResourceManager.GetString("item_headacc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap md_dummy {
            get {
                object obj = ResourceManager.GetObject("md_dummy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yowane Haku.
        /// </summary>
        public static string name_haku {
            get {
                return ResourceManager.GetString("name_haku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KAITO.
        /// </summary>
        public static string name_kaito {
            get {
                return ResourceManager.GetString("name_kaito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kagamine Len.
        /// </summary>
        public static string name_len {
            get {
                return ResourceManager.GetString("name_len", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Megurine Luka.
        /// </summary>
        public static string name_luka {
            get {
                return ResourceManager.GetString("name_luka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MEIKO.
        /// </summary>
        public static string name_meiko {
            get {
                return ResourceManager.GetString("name_meiko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hatsune Miku.
        /// </summary>
        public static string name_miku {
            get {
                return ResourceManager.GetString("name_miku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akita Neru.
        /// </summary>
        public static string name_neru {
            get {
                return ResourceManager.GetString("name_neru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kagamine Rin.
        /// </summary>
        public static string name_rin {
            get {
                return ResourceManager.GetString("name_rin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sakine Meiko.
        /// </summary>
        public static string name_sakine {
            get {
                return ResourceManager.GetString("name_sakine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kasane Teto.
        /// </summary>
        public static string name_teto {
            get {
                return ResourceManager.GetString("name_teto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured whilst downloading..
        /// </summary>
        public static string notice_download_fail {
            get {
                return ResourceManager.GetString("notice_download_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not download this file:.
        /// </summary>
        public static string notice_download_failed_file {
            get {
                return ResourceManager.GetString("notice_download_failed_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All downloads have finished..
        /// </summary>
        public static string notice_download_finished {
            get {
                return ResourceManager.GetString("notice_download_finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please try again..
        /// </summary>
        public static string notice_try_again {
            get {
                return ResourceManager.GetString("notice_try_again", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have unsaved changes, are you sure you want to exit Armoire?.
        /// </summary>
        public static string notice_unsaved {
            get {
                return ResourceManager.GetString("notice_unsaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update downloaded..
        /// </summary>
        public static string notice_update {
            get {
                return ResourceManager.GetString("notice_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are using the latest version..
        /// </summary>
        public static string notice_update_newest {
            get {
                return ResourceManager.GetString("notice_update_newest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restarting Armoire..
        /// </summary>
        public static string notice_update2 {
            get {
                return ResourceManager.GetString("notice_update2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Object.
        /// </summary>
        public static string obj_add {
            get {
                return ResourceManager.GetString("obj_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive File Name.
        /// </summary>
        public static string obj_arch {
            get {
                return ResourceManager.GetString("obj_arch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Object(s).
        /// </summary>
        public static string obj_del {
            get {
                return ResourceManager.GetString("obj_del", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Object(s).
        /// </summary>
        public static string obj_dupe {
            get {
                return ResourceManager.GetString("obj_dupe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name.
        /// </summary>
        public static string obj_file {
            get {
                return ResourceManager.GetString("obj_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texture File Name.
        /// </summary>
        public static string obj_texture {
            get {
                return ResourceManager.GetString("obj_texture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the new text..
        /// </summary>
        public static string replace_new {
            get {
                return ResourceManager.GetString("replace_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the old text..
        /// </summary>
        public static string replace_old {
            get {
                return ResourceManager.GetString("replace_old", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select PNG File.
        /// </summary>
        public static string select_png {
            get {
                return ResourceManager.GetString("select_png", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates on launch:.
        /// </summary>
        public static string settings_autocheck {
            get {
                return ResourceManager.GetString("settings_autocheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string settings_autocheck_off {
            get {
                return ResourceManager.GetString("settings_autocheck_off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string settings_autocheck_on {
            get {
                return ResourceManager.GetString("settings_autocheck_on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set DMA Information Path.
        /// </summary>
        public static string settings_dma {
            get {
                return ResourceManager.GetString("settings_dma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Game Data Path.
        /// </summary>
        public static string settings_game {
            get {
                return ResourceManager.GetString("settings_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Sprite.
        /// </summary>
        public static string spr_add {
            get {
                return ResourceManager.GetString("spr_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Sprite(s).
        /// </summary>
        public static string spr_del {
            get {
                return ResourceManager.GetString("spr_del", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Sprite(s).
        /// </summary>
        public static string spr_dupe {
            get {
                return ResourceManager.GetString("spr_dupe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Sprite Set.
        /// </summary>
        public static string spr_set_add {
            get {
                return ResourceManager.GetString("spr_set_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Sprite Set(s).
        /// </summary>
        public static string spr_set_del {
            get {
                return ResourceManager.GetString("spr_set_del", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Sprite Set(s).
        /// </summary>
        public static string spr_set_dupe {
            get {
                return ResourceManager.GetString("spr_set_dupe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character Items.
        /// </summary>
        public static string tab_chritm {
            get {
                return ResourceManager.GetString("tab_chritm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessories &amp; Hair.
        /// </summary>
        public static string tab_custom {
            get {
                return ResourceManager.GetString("tab_custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DB Editors.
        /// </summary>
        public static string tab_db {
            get {
                return ResourceManager.GetString("tab_db", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modules.
        /// </summary>
        public static string tab_module {
            get {
                return ResourceManager.GetString("tab_module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings/Update.
        /// </summary>
        public static string tab_setting {
            get {
                return ResourceManager.GetString("tab_setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Themes.
        /// </summary>
        public static string tab_theme {
            get {
                return ResourceManager.GetString("tab_theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Texture.
        /// </summary>
        public static string tex_add {
            get {
                return ResourceManager.GetString("tex_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Texture.
        /// </summary>
        public static string tex_chg {
            get {
                return ResourceManager.GetString("tex_chg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Replacement.
        /// </summary>
        public static string tex_chg_add {
            get {
                return ResourceManager.GetString("tex_chg_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Replacement.
        /// </summary>
        public static string tex_chg_del {
            get {
                return ResourceManager.GetString("tex_chg_del", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Texture(s).
        /// </summary>
        public static string tex_del {
            get {
                return ResourceManager.GetString("tex_del", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Texture(s).
        /// </summary>
        public static string tex_dupe {
            get {
                return ResourceManager.GetString("tex_dupe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original Texture.
        /// </summary>
        public static string tex_org {
            get {
                return ResourceManager.GetString("tex_org", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eye (Left).
        /// </summary>
        public static string texture_eye_l {
            get {
                return ResourceManager.GetString("texture_eye_l", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eye (Right).
        /// </summary>
        public static string texture_eye_r {
            get {
                return ResourceManager.GetString("texture_eye_r", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eyebrows.
        /// </summary>
        public static string texture_eyebrow {
            get {
                return ResourceManager.GetString("texture_eyebrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eyelashes.
        /// </summary>
        public static string texture_eyelash {
            get {
                return ResourceManager.GetString("texture_eyelash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Face.
        /// </summary>
        public static string texture_face {
            get {
                return ResourceManager.GetString("texture_face", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        public static string theme_blue {
            get {
                return ResourceManager.GetString("theme_blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default (Dark).
        /// </summary>
        public static string theme_default {
            get {
                return ResourceManager.GetString("theme_default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string theme_light {
            get {
                return ResourceManager.GetString("theme_light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pink.
        /// </summary>
        public static string theme_pink {
            get {
                return ResourceManager.GetString("theme_pink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Violet.
        /// </summary>
        public static string theme_violet {
            get {
                return ResourceManager.GetString("theme_violet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object Database Editor.
        /// </summary>
        public static string title_edit_obj {
            get {
                return ResourceManager.GetString("title_edit_obj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprite Database Editor.
        /// </summary>
        public static string title_edit_spr {
            get {
                return ResourceManager.GetString("title_edit_spr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texture Database Editor.
        /// </summary>
        public static string title_edit_tex {
            get {
                return ResourceManager.GetString("title_edit_tex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texture Picker.
        /// </summary>
        public static string title_texture {
            get {
                return ResourceManager.GetString("title_texture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wizard.
        /// </summary>
        public static string title_wizard {
            get {
                return ResourceManager.GetString("title_wizard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version is available..
        /// </summary>
        public static string update_new_found {
            get {
                return ResourceManager.GetString("update_new_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to update?.
        /// </summary>
        public static string update_new_found_2 {
            get {
                return ResourceManager.GetString("update_new_found_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is case sensitive. This only applies to selected items..
        /// </summary>
        public static string warn_case_sensitive {
            get {
                return ResourceManager.GetString("warn_case_sensitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Costumes must not be empty..
        /// </summary>
        public static string warn_costume_empty {
            get {
                return ResourceManager.GetString("warn_costume_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This item could not be deleted..
        /// </summary>
        public static string warn_delete {
            get {
                return ResourceManager.GetString("warn_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will delete all entries, are you sure?.
        /// </summary>
        public static string warn_delete_all {
            get {
                return ResourceManager.GetString("warn_delete_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is not a valid Project DIVA Mega Mix+ directory..
        /// </summary>
        public static string warn_divadir_wrong {
            get {
                return ResourceManager.GetString("warn_divadir_wrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a value..
        /// </summary>
        public static string warn_enter_value {
            get {
                return ResourceManager.GetString("warn_enter_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while reading the files in your game directory. Error in:.
        /// </summary>
        public static string warn_error_read {
            get {
                return ResourceManager.GetString("warn_error_read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while saving your file. Please try again..
        /// </summary>
        public static string warn_error_save {
            get {
                return ResourceManager.GetString("warn_error_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something is wrong with the file you selected for this item. It doesn&apos;t look like a .farc format file..
        /// </summary>
        public static string warn_file_error {
            get {
                return ResourceManager.GetString("warn_file_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To save, you must select a file first..
        /// </summary>
        public static string warn_flop_save {
            get {
                return ResourceManager.GetString("warn_flop_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A generic error occurred..
        /// </summary>
        public static string warn_generic {
            get {
                return ResourceManager.GetString("warn_generic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the amount to increase the ID by..
        /// </summary>
        public static string warn_increment {
            get {
                return ResourceManager.GetString("warn_increment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select an item first..
        /// </summary>
        public static string warn_item_not_sel {
            get {
                return ResourceManager.GetString("warn_item_not_sel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no items in the wizard..
        /// </summary>
        public static string warn_no_items {
            get {
                return ResourceManager.GetString("warn_no_items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please give your mod a name..
        /// </summary>
        public static string warn_no_name {
            get {
                return ResourceManager.GetString("warn_no_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only 2 objects may be used..
        /// </summary>
        public static string warn_object_limit {
            get {
                return ResourceManager.GetString("warn_object_limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have unsaved changes, do you wish to quit without saving?.
        /// </summary>
        public static string warn_unsaved {
            get {
                return ResourceManager.GetString("warn_unsaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This .
        /// </summary>
        public static string warn_used_0 {
            get {
                return ResourceManager.GetString("warn_used_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eden Project mod folder detected. This file will not be read as it is known to cause issues with Armoire and other mods..
        /// </summary>
        public static string warn_virus {
            get {
                return ResourceManager.GetString("warn_virus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This window is already open..
        /// </summary>
        public static string warn_window {
            get {
                return ResourceManager.GetString("warn_window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your items, something is not set correctly..
        /// </summary>
        public static string warn_wizard_problem {
            get {
                return ResourceManager.GetString("warn_wizard_problem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Properties.
        /// </summary>
        public static string window_item {
            get {
                return ResourceManager.GetString("window_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item List.
        /// </summary>
        public static string window_list_item {
            get {
                return ResourceManager.GetString("window_list_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notice.
        /// </summary>
        public static string window_notice {
            get {
                return ResourceManager.GetString("window_notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object DB.
        /// </summary>
        public static string window_obj {
            get {
                return ResourceManager.GetString("window_obj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object Entry Editor.
        /// </summary>
        public static string window_obj_edit {
            get {
                return ResourceManager.GetString("window_obj_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Preset.
        /// </summary>
        public static string window_preset {
            get {
                return ResourceManager.GetString("window_preset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprite DB.
        /// </summary>
        public static string window_spr {
            get {
                return ResourceManager.GetString("window_spr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprite Entry Editor.
        /// </summary>
        public static string window_spr_edit {
            get {
                return ResourceManager.GetString("window_spr_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texture DB.
        /// </summary>
        public static string window_tex {
            get {
                return ResourceManager.GetString("window_tex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texture Replacement Editor.
        /// </summary>
        public static string window_tex_chg {
            get {
                return ResourceManager.GetString("window_tex_chg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Existing.
        /// </summary>
        public static string wizard_add_exist {
            get {
                return ResourceManager.GetString("wizard_add_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New.
        /// </summary>
        public static string wizard_add_new {
            get {
                return ResourceManager.GetString("wizard_add_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customize Item.
        /// </summary>
        public static string wizard_customise {
            get {
                return ResourceManager.GetString("wizard_customise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module.
        /// </summary>
        public static string wizard_module {
            get {
                return ResourceManager.GetString("wizard_module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove All.
        /// </summary>
        public static string wizard_remove {
            get {
                return ResourceManager.GetString("wizard_remove", resourceCulture);
            }
        }
    }
}
